# build-docker.yml

# 填入到github的secrets中 https://github.com/test/repo/settings/secrets/actions

name: 构建和上传镜像到腾讯云私有镜像仓库

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      # 设置镜像名称，请根据你的实际情况修改
      IMAGE_NAME: my-app
      # 腾讯云镜像仓库命名空间，请替换为你的命名空间
      TCR_NAMESPACE: test-hk
      TZ: Asia/Shanghai # 在这里设置时区
      REGISTRY: hkccr.ccs.tencentyun.com # 腾讯云镜像仓库地址
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Docker image tag with timestamp
        id: tag
        run: |
          # 验证时区设置
          echo "当前时区:"
          date
          # 生成时间戳标签，格式为 2025-10-10-12-00-00(精确到秒)
          TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
          echo "生成的时间戳: $TIMESTAMP"
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          # 设置镜像标签，格式为 hkccr.ccs.tencentyun.com/命名空间/镜像名:时间戳
          echo "IMAGE_TAG=${{ env.REGISTRY }}/${{ env.TCR_NAMESPACE }}/${{ env.IMAGE_NAME }}:$TIMESTAMP" >> $GITHUB_ENV

      - name: Log in to Tencent Cloud Container Registry
        uses: docker/login-action@v3
        with:
          # https://github.com/test/repo/settings/secrets/actions
          # https://github.com/docker/login-action
          # 腾讯云镜像仓库地址 https://console.cloud.tencent.com/tcr/repository/
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.TENCENT_USERNAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_TAG }}

  # https://github.com/appleboy/ssh-action/blob/master/README.zh-cn.md
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # 明确依赖构建任务，等构建完成在执行部署
    steps:
      - name: Execute deployment script on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }} # 服务器 IP 或域名
          username: ${{ secrets.SERVER_USERNAME }} # SSH 用户名
          password: ${{ secrets.SERVER_PASSWORD }} # SSH 密码
          # 部署成功后自动执行服务端脚本文件
          script: 'sh /www/docker-deploy.sh'
